/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jotwot.glb --transform --draco --meshopt 
Files: jotwot.glb [5.38MB] > /home/chilsu/Documents/dvmWork/APOGEE-26-web/public/models/jotwot-transformed.glb [4.27MB] (21%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/jotwot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial001} position={[0, 1.014, -0.568]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.advertising_screens_texture_01} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.003']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Material.009']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.004']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.PaletteMaterial002} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_101.geometry} material={materials['Material.008']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_180.geometry} material={materials['Material.005']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_186.geometry} material={materials['Material.002']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_189.geometry} material={materials.PaletteMaterial003} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.bridgeUV} position={[9.609, 4.703, -0.464]} rotation={[-Math.PI, 0.15, -Math.PI]} scale={[0.237, 0.16, 0.237]} />
      <mesh geometry={nodes.BézierCurve062.geometry} material={materials['Mystical mesh']} position={[8.899, 4.703, 1.167]} rotation={[-3.081, 1.304, -0.041]} scale={[-1.172, -0.974, -0.998]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Braided metal']} position={[5.581, 2.262, -0.617]} scale={[0.14, 0.236, 0.14]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.hologram} position={[12.531, 3.369, -1.046]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.041, 0.494, 0.494]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.body} position={[0.466, 1.023, 0.146]} rotation={[0.025, 0.443, -0.059]} scale={0.043} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material} position={[0.466, 1.023, 0.146]} rotation={[0.025, 0.443, -0.059]} scale={0.043} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.PaletteMaterial004} position={[13.442, 4.287, 0.115]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.575, 0.004, 0.007]} />
      <mesh geometry={nodes.Plane435.geometry} material={nodes.Plane435.material} position={[-4.207, 2.434, 0.452]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 1.9]} />
      <mesh geometry={nodes.Earth_globe_glowing_hologram.geometry} material={materials['Earth Surface.002']} position={[7.979, 1.046, -1.538]} rotation={[Math.PI, -0.888, Math.PI]} scale={0.733} />
      <instancedMesh args={[nodes.Cube_00.geometry, materials.Concrete, 2]} instanceMatrix={nodes.Cube_00.instanceMatrix} position={[-11.08, 2.809, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <instancedMesh args={[nodes.Cube_01.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Cube_01.instanceMatrix} position={[-11.08, 2.809, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <instancedMesh args={[nodes.Cube_02.geometry, materials.Road, 2]} instanceMatrix={nodes.Cube_02.instanceMatrix} position={[-11.08, 2.809, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <instancedMesh args={[nodes.Cube_03.geometry, materials.PaletteMaterial005, 2]} instanceMatrix={nodes.Cube_03.instanceMatrix} position={[-11.08, 2.809, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <instancedMesh args={[nodes.Cube_04.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Cube_04.instanceMatrix} position={[-11.08, 2.809, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <instancedMesh args={[nodes.Cube_05.geometry, materials.PaletteMaterial001, 2]} instanceMatrix={nodes.Cube_05.instanceMatrix} position={[-11.08, 2.809, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
    </group>
  )
}

useGLTF.preload('/jotwot-transformed.glb')
