/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/landing/car5.0.glb --transform --draco --instance --types 
Files: src/assets/3d/landing/car5.0.glb [2.31MB] > /home/ishaan/Documents/DVM/APOGEE-26-web/car5.0-transformed.glb [396.24KB] (83%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    meshId5_name: THREE.Mesh
    meshId5_name_1: THREE.Mesh
    meshId5_name_2: THREE.Mesh
    meshId5_name_3: THREE.Mesh
    meshId5_name_4: THREE.Mesh
    meshId5_name_5: THREE.Mesh
    spinner003: THREE.Mesh
  }
  materials: {
    ['white light']: THREE.MeshStandardMaterial
    ex: THREE.MeshStandardMaterial
    int: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    ['red light']: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    ['lights purple']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/car5.0-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.492}>
        <mesh geometry={nodes.meshId5_name.geometry} material={materials['white light']} />
        <mesh geometry={nodes.meshId5_name_1.geometry} material={materials.ex} />
        <mesh geometry={nodes.meshId5_name_2.geometry} material={materials.int} />
        <mesh geometry={nodes.meshId5_name_3.geometry} material={materials.mirror} />
        <mesh geometry={nodes.meshId5_name_4.geometry} material={materials['red light']} />
        <mesh geometry={nodes.meshId5_name_5.geometry} material={materials.blue} />
      </group>
      <mesh geometry={nodes.spinner003.geometry} material={materials['lights purple']} rotation={[Math.PI / 2, 0, 0]} scale={1.492} />
    </group>
  )
}

useGLTF.preload('/car5.0-transformed.glb')
