/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/city33-transformed.glb --transform --draco --instance --types --simplify 
Files: public/models/city33-transformed.glb [4.44MB] > /home/ishaan/Documents/DVM/APOGEE-26-web/city33-transformed-transformed.glb [4.06MB] (9%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'ComingHolo' | 'HoloEnd' | 'Idle' | 'ViewHolo'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_11: THREE.Mesh
    Object_14: THREE.Mesh
    Object_26: THREE.Mesh
    Object_32: THREE.Mesh
    Object_41: THREE.Mesh
    Object_50: THREE.Mesh
    Object_68: THREE.Mesh
    Object_101: THREE.Mesh
    Object_180: THREE.Mesh
    Object_186: THREE.Mesh
    Object_189: THREE.Mesh
    Cube031: THREE.Mesh
    BézierCurve062: THREE.Mesh
    Cube046: THREE.Mesh
    Plane003: THREE.Mesh
    Plane007: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7001: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    advertising_screens_texture_01: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    bridgeUV: THREE.MeshStandardMaterial
    ['Mystical mesh']: THREE.MeshBasicMaterial
    ['Braided metal']: THREE.MeshStandardMaterial
    hologram: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    Concrete: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshPhysicalMaterial
    body: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/city33-transformed-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="GLTF_created_0" position={[0.466, 1.023, 0.146]} rotation={[0.025, 0.443, -0.059]} scale={0.043}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
        </group>
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.001']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial001} position={[0, 1.014, -0.568]} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.advertising_screens_texture_01} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.003']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials['Material.009']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.004']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.PaletteMaterial002} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials['Material.008']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.005']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.002']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.PaletteMaterial003} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials.bridgeUV} position={[9.609, 4.703, -0.464]} rotation={[-Math.PI, 0.15, -Math.PI]} scale={[0.237, 0.16, 0.237]} />
        <mesh name="BézierCurve062" geometry={nodes.BézierCurve062.geometry} material={materials['Mystical mesh']} position={[8.899, 4.703, 1.167]} rotation={[-3.081, 1.304, -0.041]} scale={[-1.172, -0.974, -0.998]} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials['Braided metal']} position={[5.581, 2.262, -0.617]} scale={[0.14, 0.236, 0.14]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.hologram} position={[1.329, 1.209, 0.336]} rotation={[Math.PI / 2, 0, -2.014]} scale={[0.431, 0.204, 0.204]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.PaletteMaterial005} position={[13.442, 4.287, 0.115]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.575, 0.004, 0.007]} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Concrete} position={[-11.08, 1.96, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Road} position={[-11.08, 1.96, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
        <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials.PaletteMaterial006} position={[-11.08, 1.96, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.body} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material} skeleton={nodes.Object_8.skeleton} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial004} skeleton={nodes.Object_9.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/city33-transformed-transformed.glb')
