/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dvmlogowide-v1.glb --transform --draco --instance --types --keepnames 
Files: public/models/dvmlogowide-v1.glb [3.1KB] > /home/ishaan/Documents/DVM/APOGEE-26-web/dvmlogowide-v1-transformed.glb [2.84KB] (8%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/dvmlogowide-v1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[-0.35, -0.125, -0.56]} rotation={[Math.PI / 2, 0, 0]} scale={0.064} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[0.616, 0.125, -0.56]} rotation={[Math.PI / 2, 0, 0]} scale={[0.088, 0.087, 0.087]} />
    </group>
  )
}

useGLTF.preload('/dvmlogowide-v1-transformed.glb')
