/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/jotkot-transformed-transformed.glb --instance --types 
Files: public/models/jotkot-transformed-transformed.glb [4.1MB] > /home/ishaan/Documents/DVM/APOGEE-26-web/jotkot-transformed-transformed-transformed.glb [4.06MB] (1%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_11: THREE.Mesh
    Object_14: THREE.Mesh
    Object_26: THREE.Mesh
    Object_32: THREE.Mesh
    Object_41: THREE.Mesh
    Object_50: THREE.Mesh
    Object_68: THREE.Mesh
    Object_101: THREE.Mesh
    Object_180: THREE.Mesh
    Object_186: THREE.Mesh
    Object_189: THREE.Mesh
    Cube031: THREE.Mesh
    BézierCurve062: THREE.Mesh
    Cube046: THREE.Mesh
    Plane: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Plane007: THREE.Mesh
    Earth_globe_glowing_hologram: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7001: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    advertising_screens_texture_01: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    bridgeUV: THREE.MeshStandardMaterial
    ['Mystical mesh']: THREE.MeshBasicMaterial
    ['Braided metal']: THREE.MeshStandardMaterial
    hologram: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    ['Earth Surface.002']: THREE.MeshStandardMaterial
    Concrete: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/jotkot-transformed-transformed-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial001} position={[0, 1.014, -0.568]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.advertising_screens_texture_01} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.003']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Material.009']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Material.004']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.PaletteMaterial002} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_101.geometry} material={materials['Material.008']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_180.geometry} material={materials['Material.005']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_186.geometry} material={materials['Material.002']} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Object_189.geometry} material={materials.PaletteMaterial003} position={[0, 1.014, -0.568]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.bridgeUV} position={[9.609, 4.703, -0.464]} rotation={[-Math.PI, 0.15, -Math.PI]} scale={[0.237, 0.16, 0.237]} />
      <mesh geometry={nodes.BézierCurve062.geometry} material={materials['Mystical mesh']} position={[8.899, 4.703, 1.167]} rotation={[-3.081, 1.304, -0.041]} scale={[-1.172, -0.974, -0.998]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials['Braided metal']} position={[5.581, 2.262, -0.617]} scale={[0.14, 0.236, 0.14]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.hologram} position={[12.531, 3.369, -1.046]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.041, 0.494, 0.494]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.body} position={[0.466, 1.023, 0.146]} rotation={[0.025, 0.443, -0.059]} scale={0.043} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material} position={[0.466, 1.023, 0.146]} rotation={[0.025, 0.443, -0.059]} scale={0.043} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.PaletteMaterial004} position={[13.442, 4.287, 0.115]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.575, 0.004, 0.007]} />
      <mesh geometry={nodes.Earth_globe_glowing_hologram.geometry} material={materials['Earth Surface.002']} position={[7.979, 1.046, -1.538]} rotation={[Math.PI, -0.888, Math.PI]} scale={0.733} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Concrete} position={[-11.08, 1.96, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Road} position={[-11.08, 1.96, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
      <mesh geometry={nodes.Object_7001.geometry} material={materials.PaletteMaterial005} position={[-11.08, 1.96, -0.335]} rotation={[0, 1.52, 0]} scale={[0.072, 0.186, 0.101]} />
    </group>
  )
}

useGLTF.preload('/jotkot-transformed-transformed-transformed.glb')
