const assetList = {
  images: [
    // Preloader
    '/img/preloader/bg.png',
    // '/img/preloader/dvm-pixelated.png',

    // Landing Page
    '/img/landing/reg_btn22.png',
    '/img/landing/modal_border.png',
    '/img/landing/modal_border_mobile.png',

    // About Us
    '/img/aboutUs/about-us-bg.png',
    '/img/aboutUs/video-frame.png',
    '/img/aboutUs/video-placeholder.png',
    '/svg/aboutUs/arrow.svg',
    '/svg/aboutUs/icon-ring.svg',
    '/svg/aboutUs/instagram.svg',
    '/svg/aboutUs/linkedin.svg',
    '/svg/aboutUs/twitter.svg',
    '/svg/aboutUs/video-frame.svg',
    '/svg/aboutUs/youtube.svg',

    // Contact Us
    '/img/contacts/bg.png',
    '/img/contacts/cardBG.png',
    '/img/contacts/cardBorder.png',
    '/img/contacts/Anagha_Sharma_PCrA.png',
    '/img/contacts/Atharv_Agarwal_-_Department_of_Visual_Media.png',
    '/img/contacts/Aurvind_Mohanty_Art_Design___Publicity.png',
    '/img/contacts/Ishita_Sethi_Department_of_Paper_Evaluation_and_Presentation.png',
    '/img/contacts/Shivansh_Rastogi_-_Department_of_Sponsorship___Marketing.png',
    '/img/contacts/Shreya_Karnwal_RecNAcc.png',
    '/img/contacts/Shreyak_Shintre_-_Controls.png',
    '/img/contacts/aditya.png',
    '/img/contacts/sajal.png',

    // Events
    // '/img/events/bg.png',
    // '/img/events/art.png',
    // '/img/events/caseComp.png',
    // '/img/events/coding.png',
    // '/img/events/esummit.png',
    // '/img/events/exhibition.png',
    // '/img/events/kernel.png',
    // '/img/events/quiz.png',
    // '/img/events/sample.png',
    // '/img/events/coding1.png',
    // '/img/events/esummit1.png',
    // '/img/events/exhibition1.png',
    // '/img/events/misc1.png',
    // '/img/events/backBtn.png',
    // '/svg/events/arrows.svg',
    // '/svg/events/call.svg',
    // '/svg/events/frame.svg',
    // '/svg/events/loc.svg',
    // '/svg/events/time.svg',

    // Speakers
    // '/img/speakers/speakerBg.png',
    // '/img/speakers/imageFrame.png',
    // '/img/speakers/mobileWheel.png',
    // '/img/speakers/backBtn.png',
    // '/img/speakers/2021/Kiran Karnik.jpg',
    // '/img/speakers/2021/Prof. Muhammad Yunus.jpg',
    // '/img/speakers/2021/Reinhold Messner.jpg',
    // '/img/speakers/2021/Shri. Nitin Gadkari.jpg',
    // '/img/speakers/2021/Suresh Prabhu.jpg',
    // '/img/speakers/2021/Susan Bennett.jpg',
    // '/img/speakers/2021/Vint Cerf.jpg',
    // '/img/speakers/2021/avijitt dutt.jpg',
    // '/img/speakers/2021/hcv.jpg',
    // '/img/speakers/2021/ms bitta.jpg',
    // '/img/speakers/2021/ruth.jpg',
    // '/img/speakers/2022/Dr Ajay Kumar.jpg',
    // '/img/speakers/2022/Dr Henry Throop.jpg',
    // '/img/speakers/2022/Dr. Soumya Swaminathan.jpg',
    // '/img/speakers/2022/Duvvuri_Subbarao_(cropped).jpg',
    // '/img/speakers/2022/Gauri_Shinde.jpg',
    // '/img/speakers/2022/Jeffrey Archer.jpg',
    // '/img/speakers/2022/Ms Deepa Mallik.jpg',
    // '/img/speakers/2022/Zainab Nagin Cox.jpg',
    // '/img/speakers/2023/Dr. V. K. Saraswat.jpg',
    // '/img/speakers/2023/Mr Dibakar Banerjee.jpg',
    // '/img/speakers/2023/Mr R.B. Ramesh.jpg',
    // '/img/speakers/2023/Prof. K. Vijayraghavan.jpg',
    // '/img/speakers/2023/S Nagarajan.jpg',
    // '/img/speakers/2023/sainath.jpg',
    // '/img/speakers/2024/Dinesh Trivedi.jpg',
    // '/img/speakers/2024/Dr Ajay Bhushan Pandey.jpg',
    // '/img/speakers/2024/Roopa Ganguly.jpg',
    // '/img/speakers/2024/Shivshankar Menon.jpg',
    // '/img/speakers/2024/Vinod G. Khandare.jpg',
    // '/img/speakers/2025/Dilip D_Souza.jpg',
    // '/img/speakers/2025/Dr Anil Kumar Gupta.jpg',
    // '/img/speakers/2025/Dr Tirthankar Patnaik.jpg',
    // '/img/speakers/2025/Dr Vijender Singh Chauhan.jpg',
    // '/img/speakers/2025/Dr. V. Anantha Nageswaran.png',
    // '/img/speakers/2025/IMG-20250401-WA0149.jpg',
    // '/img/speakers/2025/Mr Abhay Kumar.jpg',
    // '/img/speakers/2025/Ms Nidhi Bansal.jpg',
    // '/img/speakers/2026/AmitabhSinha.png',
    // '/img/speakers/2026/DrShaileshNayak.png',
    // '/img/speakers/2026/OmPrakashSrivastava.png',
    // '/img/speakers/2026/PrabhladaRamaRao.png',
    // '/img/speakers/2026/sanjayaBaru.png',
    // '/svg/speakers/activeFramwe.svg',
    // '/svg/speakers/activeSpeakerName.svg',
    // '/svg/speakers/arrows.svg',
    // '/svg/speakers/fifth.svg',
    // '/svg/speakers/first.svg',
    // '/svg/speakers/fourth.svg',
    // '/svg/speakers/frameEvents.svg',
    // '/svg/speakers/imageFrame.svg',
    // '/svg/speakers/mobileNameFrame.svg',
    // '/svg/speakers/mobileYearFrame.svg',
    // '/svg/speakers/nameFrame.svg',
    // '/svg/speakers/second.svg',
    // '/svg/speakers/speakerName.svg',
    // '/svg/speakers/third.svg',
    // '/svg/speakers/yearFrame.svg',

    // Hamburger Menu
    '/img/ham/dott.png',
    '/img/ham/luv_dvm.png',
    '/img/ham/textBottom.png',

    // General/Main
    '/apogee_w_spons.png',
  ],
  models: [
    '/models/starjunction-transformed.glb',
    '/models/car5.0-transformed.glb',
  ],
};

export default assetList;
