const assetList = {
  landing: [
    "/img/contacts/bg.png",
    "/img/contacts/cardBG.png",
    "/img/contacts/cardBorder.png",
    "/img/contacts/sample.png",
    "/apogee26logo.png",
    // "/img/contacts/sample2.png",
    '/img/contacts/bg.png',
    '/img/contacts/cardBG.png',
    '/img/contacts/cardBorder.png',
    '/img/contacts/Anagha_Sharma_PCrA.png',
    '/img/contacts/Atharv_Agarwal_-_Department_of_Visual_Media.png',
    '/img/contacts/Aurvind_Mohanty_Art_Design___ity.png',
    '/img/contacts/Ishita_Sethi_Department_of_Paper_Evaluation_and_Presentation.png',
    '/img/contacts/Shivansh_Rastogi_-_Department_of_Sponsorship___Marketing.png',
    '/img/contacts/Shreya_Karnwal_RecNAcc.png',
    '/img/contacts/Shreyak_Shintre_-_Controls.png',
    '/img/contacts/aditya.png',
    '/img/contacts/sajal.png',
    '/img/landing/border.png',
    '/img/landing/reg_portal.png',
    '/img/aboutUs/about-us-bg.png',
    '/img/aboutUs/video-frame.png',
    '/img/aboutUs/video-placeholder.png',
    '/img/preloader/bg.png',
    '/svg/aboutUs/arrow.svg',
    '/svg/aboutUs/icon-ring.svg',
    '/svg/aboutUs/instagram.svg',
    '/svg/aboutUs/linkedin.svg',
    '/svg/aboutUs/twitter.svg',
    '/svg/aboutUs/video-frame.svg',
    '/svg/aboutUs/youtube.svg',
  ],
};

export default assetList;
