/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import  type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_11: THREE.Mesh
    Object_14: THREE.Mesh
    Object_26: THREE.Mesh
    Object_32: THREE.Mesh
    Object_41: THREE.Mesh
    Object_50: THREE.Mesh
    Object_68: THREE.Mesh
    Object_101: THREE.Mesh
    Object_180: THREE.Mesh
    Object_186: THREE.Mesh
    Object_189: THREE.Mesh
    Cube031: THREE.Mesh
    BézierCurve062: THREE.Mesh
    Cube046: THREE.Mesh
    Plane: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Plane007: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7001: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    advertising_screens_texture_01: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    bridgeUV: THREE.MeshStandardMaterial
    ['Mystical mesh']: THREE.MeshBasicMaterial
    ['Braided metal']: THREE.MeshStandardMaterial
    hologram: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    Concrete: THREE.MeshStandardMaterial
    Road: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
  }
}

export function CityModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/public/models/citybest.glb') as unknown as  GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        {/* adv board */}
        <mesh
          name="Object_11"
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['Material.001']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        {/* Geometry of windows etc, glass */}
        <mesh
          name="Object_14"
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.PaletteMaterial001}
          position={[0, 1.01412129, -0.56755769]}
        />
        {/* Black screens */}
        <mesh
          name="Object_26"
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.advertising_screens_texture_01}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        {/* Countdown+road */}
        <mesh
          name="Object_32"
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials['Material.003']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        {/* Black color of buildings */}
        <mesh
          name="Object_41"
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials['Material.009']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        <mesh
          name="Object_50"
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials['Material.004']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        <mesh
          name="Object_68"
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials.PaletteMaterial002}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        {/* Front one pink colored board */}
        <mesh
          name="Object_101"
          castShadow
          receiveShadow
          geometry={nodes.Object_101.geometry}
          material={materials['Material.008']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        <mesh
          name="Object_180"
          castShadow
          receiveShadow
          geometry={nodes.Object_180.geometry}
          material={materials['Material.005']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        {/* Adv */}
        <mesh
          name="Object_186"
          castShadow
          receiveShadow
          geometry={nodes.Object_186.geometry}
          material={materials['Material.002']}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        <mesh
          name="Object_189"
          castShadow
          receiveShadow
          geometry={nodes.Object_189.geometry}
          material={materials.PaletteMaterial003}
          position={[0, 1.01412129, -0.56755769]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.00060234}
        />
        {/* Above bridges */}
        <mesh
          name="Cube031"
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={materials.bridgeUV}
          position={[9.60933208, 4.70252323, -0.4637031]}
          rotation={[-Math.PI, 0.15032962, -Math.PI]}
          scale={[0.23708609, 0.16027609, 0.23708609]}
        />
        {/* Wires */}
        <mesh
          name="BézierCurve062"
          castShadow
          receiveShadow
          geometry={nodes.BézierCurve062.geometry}
          material={materials['Mystical mesh']}
          position={[8.89876747, 4.70252323, 1.16687107]}
          rotation={[-3.081238, 1.30428059, -0.04069112]}
          scale={[-1.17242849, -0.97401041, -0.99793112]}
        />
        {/* Diff bridge */}
        <mesh
          name="Cube046"
          castShadow
          receiveShadow
          geometry={nodes.Cube046.geometry}
          material={materials['Braided metal']}
          position={[5.58051395, 2.26183605, -0.6172998]}
          scale={[0.13960782, 0.23576576, 0.13960782]}
        />
        {/* //Below one is logo */}
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.hologram}
          position={[12.53145409, 3.36920047, -1.0459305]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.04093277, 0.49352551, 0.49352551]}
        />
        {/* Below two are of below hologram */}
        <mesh
          name="Object_7"
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.body}
          position={[0.46595082, 1.02259803, 0.14579016]}
          rotation={[0.0250912, 0.44258281, -0.0585318]}
          scale={[0.04307262, 0.04307262, 0.04307264]}
        />
        <mesh
          name="Object_8"
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.material}
          position={[0.46595082, 1.02259803, 0.14579016]}
          rotation={[0.0250912, 0.44258281, -0.0585318]}
          scale={[0.04307262, 0.04307262, 0.04307264]}
        />
        {/* Lights */}
        <mesh
          name="Plane007"
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials.PaletteMaterial004}
          position={[13.44158077, 4.28689814, 0.11534482]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.57453668, 0.004355, 0.00730087]}
        />
        {/* Concrete */}
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Concrete}
          position={[-11.07997802, 1.95978271, -0.33482088]}
          rotation={[8.6e-7, 1.51986583, -9.8e-7]}
          scale={[0.07241275, 0.18602849, 0.10137784]}
        />
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Road}
          position={[-11.07997802, 1.95978271, -0.33482088]}
          rotation={[8.6e-7, 1.51986583, -9.8e-7]}
          scale={[0.07241275, 0.18602849, 0.10137784]}
        />
        {/* Bridge glass */}
        <mesh
          name="Object_7001"
          castShadow
          receiveShadow
          geometry={nodes.Object_7001.geometry}
          material={materials.PaletteMaterial005}
          position={[-11.07997802, 1.95978271, -0.33482088]}
          rotation={[8.6e-7, 1.51986583, -9.8e-7]}
          scale={[0.07241275, 0.18602849, 0.10137784]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/citybest.glb')
