// import { Float, useGLTF } from "@react-three/drei";
// import { editable as e } from "@theatre/r3f";
// import { forwardRef } from "react";
// import * as THREE from "three";
// import carModel from "../../../../assets/3d/landing/car4.0.glb";
// const Infernus = forwardRef<THREE.Group>((props, ref) => {
//   const { scene } = useGLTF(carModel);

//   return (
//     <Float floatIntensity={3} rotationIntensity={0.05} speed={5}>
//       <e.group
//         theatreKey="infernus"
//         ref={ref}
//         rotation={[0, 0 , 0]}
//         position={[0.5, -6, 60]}
//         scale={[6,6,6]}
//         {...props}
//         frustumCulled={false} 
//       >
//         <primitive object={scene} />
//       </e.group>
//      </Float>
//   );
// });

// export default Infernus;

// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useEffect, useRef } from 'react'
import infernusModel from "../../../../assets/3d/landing/car1mb.glb";
import { editable as e } from '@theatre/r3f';
import { useInfernusStore } from '../../../../utils/store';

type GLTFResult = GLTF & {
  nodes: {
    meshId5_name: THREE.Mesh
    meshId5_name_1: THREE.Mesh
    meshId5_name_2: THREE.Mesh
  }
  materials: {
    mirror: THREE.MeshStandardMaterial
    ex: THREE.MeshStandardMaterial
    int: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
  }
}

export default function Infernus() {

  const infernusRef = useRef<THREE.Group>(null!);
  const setInfernus = useInfernusStore((s) => s.setInfernus);
  useEffect(() => {
    if (infernusRef.current) {
      setInfernus(infernusRef.current);
    }
  }, [setInfernus]);

  const { nodes, materials } = useGLTF(infernusModel) as unknown as GLTFResult
  return (
    <e.group
      ref={infernusRef}
      dispose={null}
      position={[0.5, -6, 60]}
      theatreKey="infernus"
      rotation={[0, 0, 0]}
      scale={[6, 6, 6]}
      frustumCulled={false} >
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.492}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name.geometry}
          material={materials.mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_1.geometry}
          material={materials.ex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_2.geometry}
          material={materials.int}
        />
      </group>
    </e.group>
  )
}

useGLTF.preload(infernusModel)

