// import { Float, useGLTF } from "@react-three/drei";
// import { editable as e } from "@theatre/r3f";
// import { forwardRef } from "react";
// import * as THREE from "three";
// import carModel from "../../../../assets/3d/landing/car4.0.glb";
// const Infernus = forwardRef<THREE.Group>((props, ref) => {
//   const { scene } = useGLTF(carModel);

//   return (
//     <Float floatIntensity={3} rotationIntensity={0.05} speed={5}>
//       <e.group
//         theatreKey="infernus"
//         ref={ref}
//         rotation={[0, 0 , 0]}
//         position={[0.5, -6, 60]}
//         scale={[6,6,6]}
//         {...props}
//         frustumCulled={false} 
//       >
//         <primitive object={scene} />
//       </e.group>
//      </Float>
//   );
// });

// export default Infernus;

// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

import * as THREE from 'three'
import { Float, useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useEffect, useRef } from 'react'
import infernusModel from "../../../../assets/3d/landing/car5.0.glb";
// import { editable as e } from '@theatre/r3f';
import { useInfernusStore } from '../../../../utils/store';
type GLTFResult = GLTF & {
  nodes: {
    meshId5_name: THREE.Mesh
    meshId5_name_1: THREE.Mesh
    meshId5_name_2: THREE.Mesh
    meshId5_name_3: THREE.Mesh
    meshId5_name_4: THREE.Mesh
    meshId5_name_5: THREE.Mesh
    spinner003: THREE.Mesh
  }
  materials: {
    ['white light']: THREE.MeshStandardMaterial
    ex: THREE.MeshStandardMaterial
    int: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    ['red light']: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    ['lights purple']: THREE.MeshStandardMaterial
  }
}

export default function Infernus() {

  const infernusRef = useRef<THREE.Group>(null!);
  const setInfernus = useInfernusStore((s) => s.setInfernus);
  useEffect(() => {
    if (infernusRef.current) {
      setInfernus(infernusRef.current);
    }
  }, [setInfernus]);

  const { nodes, materials } = useGLTF(infernusModel) as unknown as GLTFResult
  return (
    <Float floatIntensity={3} rotationIntensity={0.05} speed={5}>
    <group
      ref={infernusRef}
      dispose={null}
      position={[0.5, -3, 60]}
      // theatreKey="infernus"
      rotation={[0, 0, 0]}
      scale={[6, 6, 6]}
      frustumCulled={false} >
      <group rotation={[Math.PI / 2, 0, 0]} scale={1.492}>
         <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name.geometry}
          material={materials['white light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_1.geometry}
          material={materials.ex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_2.geometry}
          material={materials.int}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_3.geometry}
          material={materials.mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_4.geometry}
          material={materials['red light']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meshId5_name_5.geometry}
          material={materials.blue}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spinner003.geometry}
        material={materials['lights purple']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.492}
      />
    </group>
    </Float>
  )
}

useGLTF.preload(infernusModel)

// import { Float, useGLTF } from "@react-three/drei";
// import { editable as e } from "@theatre/r3f";
// import { forwardRef, useMemo, useRef } from "react";
// import * as THREE from "three";
// import { useFrame } from "@react-three/fiber";
// import carModel from "../../../../assets/3d/landing/car4.0.glb";

// const Infernus = forwardRef<THREE.Group>((props, ref) => {
//   const { scene } = useGLTF(carModel);
//   const materialRef = useRef<THREE.ShaderMaterial>(null);

//   // Neon Shader
 

//      const neonMaterial = useMemo(() => {
//   return new THREE.ShaderMaterial({
//     uniforms: {},

//     vertexShader: `
//       varying vec3 vNormal;
//       varying vec3 vViewDir;

//       void main() {
//         vec4 worldPos = modelViewMatrix * vec4(position, 1.0);

//         vNormal = normalize(normalMatrix * normal);
//         vViewDir = normalize(-worldPos.xyz); // camera direction

//         gl_Position = projectionMatrix * worldPos;
//       }
//     `,

//     fragmentShader: `
//       varying vec3 vNormal;
//       varying vec3 vViewDir;

//       void main() {

//         vec3 neonColor = vec3(214, 95, 251) / 255.0; // constant cyan

//         // View-dependent fresnel (stable during rotation)
//         float fresnel = pow(1.0 - max(dot(normalize(vNormal), normalize(vViewDir)), 0.0), 5.5);

//         vec3 glow = neonColor * ( fresnel * 1.05*0.8);

//         gl_FragColor = vec4(glow * 1.0, 1.5); // bloom-ready
//       }
//     `,

//     toneMapped: false,
//   });
// }, []);



//   // Apply shader to all meshes in GLB
//   useMemo(() => {
//     scene.traverse((child: any) => {
//       if (child.isMesh) {
//         child.material = neonMaterial;
//       }
//     });
//   }, [scene, neonMaterial]);
//   // color="rgb(214, 95, 251)"
//   // Animate time
//   useFrame((state) => {
//     if (materialRef.current) {
//       materialRef.current.uniforms.uTime.value = state.clock.elapsedTime;
//     }
//   });

//   return (
//     <Float floatIntensity={3} rotationIntensity={0.05} speed={5}>
//       <e.group
//         theatreKey="infernus"
//         ref={ref}
//         rotation={[0, 0, 0]}
//         position={[0.5, -6, 60]}
//         scale={[6, 6, 6]}
//         {...props}
//         frustumCulled={false}
//       >
//         <primitive object={scene} />
//       </e.group>
//      </Float>
//   );
// });

// export default Infernus;
