/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: born2012 (https://sketchfab.com/born2012)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-city-1-14d2eaa145ee42938e004115871adf6c
Title: Cyberpunk City - #1
*/

import { Merged, useGLTF } from '@react-three/drei'
import { createContext, useContext, useMemo, type JSX, type ReactNode } from 'react'
import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'

import { editable as e } from '@theatre/r3f'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_22: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
  }
}

const context = createContext(null as any)
export function Instances({ children, ...props }: { children: ReactNode } & JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/city1.glb') as unknown as GLTFResult
  const instances = useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_5,
      Object2: nodes.Object_22,
    }),
    [nodes]
  )
  return (
    // @ts-ignore
    <Merged meshes={instances as any} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: any) {
  const instances = useContext(context)
  return (
    <e.group {...props} theatreKey='cityModel' dispose={null}  scale={[15,30,15]} position={[0.32181*15, -0.53*30, -2.8262*15]}>
      <instances.Object rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
      <instances.Object1 rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
      <instances.Object2 rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
    </e.group>
  )
}

useGLTF.preload('/models/city1.glb')
